# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculatorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(230, 388)
        MainWindow.setMinimumSize(QtCore.QSize(230, 370))
        MainWindow.setMaximumSize(QtCore.QSize(230, 388))
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("background-color: #1C1C1C; /* Koyu siyah/gri ton */\n"
"color: white;  ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mod = QtWidgets.QPushButton(self.centralwidget)
        self.mod.setGeometry(QtCore.QRect(115, 105, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mod.sizePolicy().hasHeightForWidth())
        self.mod.setSizePolicy(sizePolicy)
        self.mod.setStyleSheet("QPushButton {\n"
"    background-color: #6B6B6B; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8F8F8F; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.mod.setDefault(False)
        self.mod.setFlat(False)
        self.mod.setObjectName("mod")
        self.div = QtWidgets.QPushButton(self.centralwidget)
        self.div.setGeometry(QtCore.QRect(169, 105, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.div.sizePolicy().hasHeightForWidth())
        self.div.setSizePolicy(sizePolicy)
        self.div.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 149, 0); /* Turuncu */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 20px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFB347; /* Üzerine gelince daha açık turuncu */\n"
"}\n"
"\n"
"")
        self.div.setDefault(False)
        self.div.setFlat(False)
        self.div.setObjectName("div")
        self.ResultScreen = QtWidgets.QLabel(self.centralwidget)
        self.ResultScreen.setGeometry(QtCore.QRect(-11, -1, 231, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        font.setPointSize(26)
        self.ResultScreen.setFont(font)
        self.ResultScreen.setStyleSheet("background-color: #1C1C1C; /* Koyu siyah/gri ton */\n"
"color: white;              /* Yazılar için beyaz */\n"
"")
        self.ResultScreen.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.ResultScreen.setObjectName("ResultScreen")
        self.plusMinusSign = QtWidgets.QPushButton(self.centralwidget)
        self.plusMinusSign.setGeometry(QtCore.QRect(61, 105, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plusMinusSign.sizePolicy().hasHeightForWidth())
        self.plusMinusSign.setSizePolicy(sizePolicy)
        self.plusMinusSign.setStyleSheet("QPushButton {\n"
"    background-color: #6B6B6B; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 16px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8F8F8F; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.plusMinusSign.setDefault(False)
        self.plusMinusSign.setFlat(False)
        self.plusMinusSign.setObjectName("plusMinusSign")
        self.AC = QtWidgets.QPushButton(self.centralwidget)
        self.AC.setGeometry(QtCore.QRect(7, 105, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AC.sizePolicy().hasHeightForWidth())
        self.AC.setSizePolicy(sizePolicy)
        self.AC.setStyleSheet("QPushButton {\n"
"    background-color: #6B6B6B; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8F8F8F; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.AC.setDefault(False)
        self.AC.setFlat(False)
        self.AC.setObjectName("AC")
        self.times = QtWidgets.QPushButton(self.centralwidget)
        self.times.setGeometry(QtCore.QRect(169, 160, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.times.sizePolicy().hasHeightForWidth())
        self.times.setSizePolicy(sizePolicy)
        self.times.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 149, 0); /* Turuncu */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 20px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFB347; /* Üzerine gelince daha açık turuncu */\n"
"}\n"
"\n"
"")
        self.times.setDefault(False)
        self.times.setFlat(False)
        self.times.setObjectName("times")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(7, 160, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seven.sizePolicy().hasHeightForWidth())
        self.seven.setSizePolicy(sizePolicy)
        self.seven.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.seven.setDefault(False)
        self.seven.setFlat(False)
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(61, 160, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eight.sizePolicy().hasHeightForWidth())
        self.eight.setSizePolicy(sizePolicy)
        self.eight.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.eight.setDefault(False)
        self.eight.setFlat(False)
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(115, 160, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nine.sizePolicy().hasHeightForWidth())
        self.nine.setSizePolicy(sizePolicy)
        self.nine.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.nine.setDefault(False)
        self.nine.setFlat(False)
        self.nine.setObjectName("nine")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(169, 215, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minus.sizePolicy().hasHeightForWidth())
        self.minus.setSizePolicy(sizePolicy)
        self.minus.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 149, 0); /* Turuncu */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFB347; /* Üzerine gelince daha açık turuncu */\n"
"}\n"
"\n"
"")
        self.minus.setDefault(False)
        self.minus.setFlat(False)
        self.minus.setObjectName("minus")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(7, 215, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.four.sizePolicy().hasHeightForWidth())
        self.four.setSizePolicy(sizePolicy)
        self.four.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.four.setDefault(False)
        self.four.setFlat(False)
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(61, 215, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.five.sizePolicy().hasHeightForWidth())
        self.five.setSizePolicy(sizePolicy)
        self.five.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.five.setDefault(False)
        self.five.setFlat(False)
        self.five.setObjectName("five")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(115, 215, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.six.sizePolicy().hasHeightForWidth())
        self.six.setSizePolicy(sizePolicy)
        self.six.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.six.setDefault(False)
        self.six.setFlat(False)
        self.six.setObjectName("six")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(169, 270, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plus.sizePolicy().hasHeightForWidth())
        self.plus.setSizePolicy(sizePolicy)
        self.plus.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 149, 0); /* Turuncu */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 20px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFB347; /* Üzerine gelince daha açık turuncu */\n"
"}\n"
"\n"
"")
        self.plus.setDefault(False)
        self.plus.setFlat(False)
        self.plus.setObjectName("plus")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(7, 270, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.one.sizePolicy().hasHeightForWidth())
        self.one.setSizePolicy(sizePolicy)
        self.one.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.one.setDefault(False)
        self.one.setFlat(False)
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(61, 270, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.two.sizePolicy().hasHeightForWidth())
        self.two.setSizePolicy(sizePolicy)
        self.two.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.two.setDefault(False)
        self.two.setFlat(False)
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(115, 270, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.three.sizePolicy().hasHeightForWidth())
        self.three.setSizePolicy(sizePolicy)
        self.three.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 18px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.three.setDefault(False)
        self.three.setFlat(False)
        self.three.setObjectName("three")
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(169, 325, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equal.sizePolicy().hasHeightForWidth())
        self.equal.setSizePolicy(sizePolicy)
        self.equal.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 149, 0); /* Turuncu */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 20px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFB347; /* Üzerine gelince daha açık turuncu */\n"
"}\n"
"\n"
"")
        self.equal.setDefault(False)
        self.equal.setFlat(False)
        self.equal.setObjectName("equal")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(11, 325, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero.sizePolicy().hasHeightForWidth())
        self.zero.setSizePolicy(sizePolicy)
        self.zero.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 20px;           /* Yazı boyutu */\n"
"    text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.zero.setDefault(False)
        self.zero.setFlat(False)
        self.zero.setObjectName("zero")
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(115, 325, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dot.sizePolicy().hasHeightForWidth())
        self.dot.setSizePolicy(sizePolicy)
        self.dot.setStyleSheet("QPushButton {\n"
"    background-color: #505050; /* Orta gri */\n"
"    color: white;              /* Beyaz yazı */\n"
"    border: none;              /* Kenarlık yok */\n"
"    border-radius: 25px;       /* Tam yuvarlak */\n"
"    padding: 15px;             /* İç boşluk */\n"
"    font-size: 20px;           /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B6B6B; /* Üzerine gelince daha açık gri */\n"
"}\n"
"")
        self.dot.setDefault(False)
        self.dot.setFlat(False)
        self.dot.setObjectName("dot")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hesap Makinesi"))
        self.mod.setText(_translate("MainWindow", "%"))
        self.div.setText(_translate("MainWindow", "÷"))
        self.ResultScreen.setText(_translate("MainWindow", "0"))
        self.plusMinusSign.setText(_translate("MainWindow", "+/-"))
        self.AC.setText(_translate("MainWindow", "AC"))
        self.times.setText(_translate("MainWindow", "x"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.minus.setText(_translate("MainWindow", "—"))
        self.four.setText(_translate("MainWindow", "4"))
        self.five.setText(_translate("MainWindow", "5"))
        self.six.setText(_translate("MainWindow", "6"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.one.setText(_translate("MainWindow", "1"))
        self.two.setText(_translate("MainWindow", "2"))
        self.three.setText(_translate("MainWindow", "3"))
        self.equal.setText(_translate("MainWindow", "="))
        self.zero.setText(_translate("MainWindow", "0"))
        self.dot.setText(_translate("MainWindow", "."))
